config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'foods#index'
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :public_recipes, only: [:index]
  resources :general_shopping_list, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    return unless user.present?

    can(:manage, Food, user_id: user.id)
    can(:manage, Recipe, user_id: user.id)

    can :read, :all
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :measurement_unit, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: 'only allows letters' }
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  validates :food, uniqueness: { scope: :recipe, message: "You can't add duplicate recipe" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show destroy]
  def index
    @foods = current_user.foods
  end

  def show
    @food
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user

    if @food.save
      redirect_to food_path(@food), notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @food.destroy
      flash[:success] = 'Deleted successfully.'
    else
      flash[:error] = 'Food is not deleted.'
    end
    redirect_to request.referrer
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:user_id, :name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  def index
    @foods = Food.includes(:recipe_foods).where(user_id: current_user.id)
    @missing_ingredients = []
    @foods.each do |food|
      total_quantity = 0
      food.recipe_foods.each do |recipe_food|
        total_quantity += recipe_food.quantity
      end
      @missing_ingredients << food if total_quantity > food.quantity
    end
    @missing_ingredients = @missing_ingredients.map do |food|
      {
        name: food.name,
        unit: food.measurement_unit,
        quantity: food.recipe_foods.sum(:quantity) - food.quantity,
        price: food.price * (food.recipe_foods.sum(:quantity) - food.quantity)
      }
    end
    @total_price = @missing_ingredients.map { |missing_ingredient| missing_ingredient[:price] }.sum
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:user, :recipe_foods, recipe_foods: [:food]).where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @current_user = current_user
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = Recipe.find(params[:recipe_id]).id
    @recipe_food.user_id = current_user.id
    if @recipe_food.save
      redirect_to recipe_path(params[:recipe_id]), notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe_food.recipe_id).where(food_id: @recipe_food.food_id)
    @recipe_foods.each(&:destroy)
    redirect_to request.referrer
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = Recipe.find(params[:recipe_id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Food was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # before_action :set_recipe, only: %i[show destroy]
  def index
    @recipes = Recipe.includes(:user).where(user_id: current_user.id)
  end

  def show
    @foods = Food.all
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:success] = 'Deleted successfully.'
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_public_params)
      redirect_to recipe_path(@recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # def set_recipe
  #   @recipe = Recipe.find(params[:id])
  # end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end

  def recipe_public_params
    params.require(:recipe).permit(:public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/pulic_recipes_helper.rb
module PulicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<tr>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td>$ <%= food.price %></td>
  <td><%= food.quantity %></td>
  <td>
    <%= link_to "Delete", food_path(food), class: "delete",
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}
              %>
  </td>
</tr>

app/views/foods/_form.html.erb
<%= form_with(model: food, html: { class: "flex-items" }) do |form| %>
  <%= render "shared/form_error_message", resource: food %>
  <div class="field">
    <%= form.text_field :name, required: true, class: "form-input", placeholder: "Food name" %>
  </div>
  <div class="field">
    <%= form.text_field :measurement_unit, required: true, class: "form-input", placeholder: "Measurment Unit(g, kg, l, ml)" %>
  </div>
  <div class="field">
    <%= form.text_field :price, required: true, class: "form-input", placeholder: "Unit price" %>
  </div>
  <div class="field">
    <%= form.number_field :quantity, required: true, class: "form-input", placeholder: "Quantity" %>
  </div>
  <div class="create__food-btn">
    <%= form.submit "Create Food", class: "button"%>
  </div>
<% end %>

app/views/foods/index.html.erb
<section class='foods-wrapper flex-items'>
  <div class="add-food flex-items">
    <div class="food-items-header">
      <h1>Foods</h1>
      <%= link_to "Add food", new_food_path, class:"button"%>
    </div>
    <% if @foods.count > 0%>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Measurment Unit</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <%= render food%>
          <% end %>
        </tbody>
      <%else%>
        <h2>No foods</h2>
      <%end%>
    </div>
  </section>

app/views/foods/new.html.erb
<section class = "recipe_new flex-items">
  <div class="new__food-container">
    <h1>New food</h1>
    <%= render "form", food: @food %>
  </div>
  <br>
</section>

app/views/foods/show.html.erb
<section class = "food-item flex-items">
  <div class="food-description flex-items">
    <h2>Food Information</h2>
    <p>Food Name: <strong><%= @food.name%></strong></p>
    <p>Measurment Unit: <strong><%=  @food.measurement_unit%></strong></p>
    <p>Quantity: <strong><%= @food.price%></strong></p>
    <p>Unit Price: <strong><%= @food.quantity%></strong></p>
  </div>
</section>

app/views/general_shopping_list/_list.html.erb
 
<tr>
  <td><%= ingredient[:name] %></td>
  <td><%= ingredient[:quantity] %> <%=ingredient[:unit]%></td>
  <td>$ <%= ingredient[:price] %></td>
</tr>

app/views/general_shopping_list/index.html.erb
<section class='general_shopping_list flex_column'>
<h1>General Shopping List</h1>
<br/>
  <% if @foods.length == 0 %>
    <h2>There are no missing ingredients that must be purchased</h2>
  <% else %>
    <div class="general-list-header">
      <h3>Amount of ingredients need to buy: <%= @missing_ingredients.length %></h3>
      <h3>Total value of foods neded: $ <%= @total_price %> </h3>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        <% @missing_ingredients.each do |ingredient| %>
          <%= render 'list', ingredient: ingredient %>
        <% end %>
      </tbody>
  <% end %>
</section>

app/views/layouts/_navbar.html.erb
<% if current_user %>
  <nav>
  <div class="home">
    <div class="nav_links">
      <%= link_to "Home" , root_path %>
    </div>
    </div>
    <div class="menu-items">
    <div class="nav_links">
      <%= link_to "Recipes" , recipes_path %>
    </div>
    <div class="nav_links">
      <%= link_to "Public Recipes" , public_recipes_path %>
    </div>
    <div class="nav_links">
      <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false }, class: "logout_button"  %>
    </div>
    </div>
  </nav>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <section class='notice-wrapper'>
      <%= render 'layouts/navbar'%>
      <p class="notice" style="color: green"><%= notice %></p>
      <p class="alert" style="color: red"><%= alert %></p>
    </section>
      <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<section class='recipes_index flex-items'>
  <div class="public__recipe-container">
    <h1>Public Recipes</h1>
    <% if @recipes.length == 0 %>
      <p>There are no public recipes yet.</p>
    <% else %>
      <%@recipes.each do |recipe|%>
        <article class="recipe_card">
          <%=link_to recipe_path(id: recipe.id) do%>
            <div>
              <h2><%=recipe.name%></h2>
              <h3 class="user__name">By: <%=recipe.user.name%></h3>
            </div>
          <%end%>
          <div>
            <p>Total food items: <%=recipe.recipe_foods.length%></p>
            <%total_price = 0%>
            <%recipe.recipe_foods.each do |recipe_food|%>
              <%price = recipe_food.quantity* recipe_food.food.price%>
              <%total_price = total_price + price%>
            <%end%>
            <p>Total price: <%=total_price%> $</p>
          </div>
        </article>
      <%end%>
    <%end%>
  </div>
</section>

app/views/recipe_foods/edit.html.erb
<section class='recipe_new flex-items'>
  <div class="update__ingredient-container">
    <h2>Update Ingredient</h2>
    <%= form_with model: [@recipe, @recipe_food], class: 'flex-items' do |f| %>
      <p>Quantity</p>
      <div class="field">
        <%= f.number_field :quantity, placeholder: 'Quantity', required: true%><br>
      </div>
      <div class="modify__ingredient-btn">
        <%= f.submit "Modify ingredient", class: "button"%>
      </div>
    <%end%>
  </div>
</div>
</section>

app/views/recipe_foods/new.html.erb
<section class='recipe_new flex-items'>
  <h2>New Ingredient</h2>
  <div class="new__ingredients">
    <%= form_with url: recipe_recipe_foods_path, class: 'flex-items', scope: :recipe_food do |f| %>
      <%= render "shared/form_error_message", resource: @recipe_food %>
      <div class="field">
        <%= f.number_field :quantity, placeholder: 'Quantity', required: true%><br>
      </div>
      <div class="field field_select">
        <%= f.collection_select(:food_id, Food.where(user_id: @current_user), :id, :name)%><br>
      </div>
      <div class="add__ingredient-btn">
        <%= f.submit "Add ingredient", class: "button"%>
      </div>
    <%end%>
  </div>
</section>

app/views/recipes/_form.html.erb
<%= form_with(model: @recipe, html: { class: "flex-items" }) do |form| %>
<%= render "shared/form_error_message", resource: @recipe %>
  <div class="field">
    <%= form.text_field :name, required: true, class: "form-input" , placeholder: "Recipe name" %>
  </div>

  <div class="field">
    <%= form.text_field :preparation_time, required: true, class: "form-input", placeholder: "Preparation time" %>
  </div>

  <div class="field">
    <%= form.text_field :cooking_time, required: true, class: "form-input", placeholder: "Cooking time" %>
  </div>

  <div class="field">
    <%= form.text_field :description, required: true, class: "form-input", placeholder:"Description" %>
  </div>

  <%= form.submit "Create recipe", class: "button"%>
<% end %>

app/views/recipes/_ingredient.html.erb
<% @foods.each do |food| %>
  <%food.recipe_foods.where(recipe_id: @recipe.id).each do |recipe_food|%>
      <tr>
            <td><%= food.name %></td>
            <td><%= recipe_food.nil? ? 0 : recipe_food.quantity%></td>
            <td>$ <%= food.price * (recipe_food.nil? ? 0 : recipe_food.quantity) %></td>
            <td>
            <% if can? :update, @recipe %>
                <%if recipe_food%>
                  <%= link_to "Modify", edit_recipe_recipe_food_path(@recipe, recipe_food)%>
                  <%= link_to "Remove", recipe_recipe_food_path(@recipe, recipe_food), class: "delete",
                    data: { turbo_method: :delete, turbo_confirm: "Are you  sure?"}
                  %>
                <% end %>
              <%else%>
                <p>No actions allowed</p>
              <%end%>
            </td>
      </tr>
  <% end %>
<% end %>

app/views/recipes/_recipe.html.erb
  <%@recipes.each_with_index do |recipe, i|%>
    <article class="recipe_card">
      <div>
        <%=link_to recipe_path(id: recipe.id) do%>
          <h2><%=recipe.name%></h2>
        <%end%>
        <%if can? :destroy, recipe%>
          <%= link_to 'REMOVE', recipe_path(recipe), class: "delete",data: {
            turbo_method: :delete, turbo_confirm: "Are you sure?"
          } %>
          <% end %>
      </div>
      <p>Recipe Description:<br><%=recipe.description%></p>
    </article>
  <%end%>

app/views/recipes/index.html.erb
<section class='recipes_index flex-items'>
  <div class="recipe__description-container">
    <h1>Recipes</h1>
    <% if @recipes.count > 0%>
      <%= render 'recipe'%>
    <% else %>
      <h2>There are no recipes yet</h2>
    <% end %>
    <div class="new__recipe-btn">
      <%=link_to "New Recipe", new_recipe_path, class: "button" %>
    </div>
  </div>
</section>

app/views/recipes/new.html.erb
<section class='recipe_new flex-items'>
  <h2>New Recipe</h2>
  <div class="recipe__container">
    <%= form_with model:Recipe, class: 'flex-items' do |f| %>
      <%= render "shared/form_error_message", resource: @recipe %>
      <div class="field">
        <%= f.text_field :name, placeholder: 'Recipe Name', value: '', required: true%><br>
      </div>
      <div class="field">
        <%= f.number_field :preparation_time, placeholder: 'Preparation Time', required: true%><br>
      </div>
      <div class="field">
        <%= f.number_field :cooking_time, placeholder: 'Cooking Time', required: true%><br>
      </div>
      <div class="field">
        <%= f.text_area :description, placeholder: 'Description', required: true%><br>
      </div>
      <div class="field-check publicity__check">
        <%= f.label :public%>
        <%= f.check_box :public, {}, true, false%><br>
      </div>
      <%= f.submit "Create Recipe", class: "button"%>
    <%end%>
  </div>
</section>

app/views/recipes/show.html.erb
<section class = "recipe-item">
  <div class="recipe__container">
    <h2> <%= @recipe.name %></h2>
    <div class='recipe_information'>
      <p>Preparation time: <%=@recipe.preparation_time%> minutes</p>
      <div class='public_logo'>
        <p><%=@recipe.public ? 'Public' : 'Not Public'%></p>
        <div class="<%=@recipe.public ? 'public' : 'not_public'%>">
          <span class="<%=@recipe.public ? 'public_switch' : 'not_public_switch'%>"></span>
        </div>
      </div>
      <p>Cooking time: <%=@recipe.cooking_time%> minutes</p>
    </div>
    <p><%=@recipe.description%></p>
    <div class='recipe_buttons'>
      <% if can? :update, @recipe %>
        <%=link_to "Generate Shopping List", general_shopping_list_index_path, class: "button" %>
        <%=link_to "Add ingredient", new_recipe_recipe_food_path(@recipe), class: "button" %>
      <% end %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= render 'ingredient'%>
      </tbody>
    </table>
  </div>
</section>

app/views/shared/_form_error_message.html.erb
<% if resource.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this food from being saved:</h2>
    <ul>
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>